import test from "node:test";
import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import { mkdtempSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { convertText, parseHyprlang, stripComment } from "../docs/converter.js";

test("stripComment ignores hashes inside quotes", () => {
  assert.equal(stripComment('foo = "bar # baz" # tail'), 'foo = "bar # baz" ');
});

test("parseHyprlang builds nested blocks and reports unmatched braces", () => {
  const parsed = parseHyprlang("decoration {\n  blur {\n    enabled = yes\n  }\n}\n}");
  assert.equal(parsed.nodes.length, 1);
  assert.deepEqual(parsed.unknown, ["line 6: unmatched closing brace"]);
});

test("convertText emits variables, nested blocks, gradients, animations, and rules", () => {
  const input = `$active = rgba(89b4faee)
$inactive = rgb(313244)

general {
  gaps_in = 4
  col.active_border = $active $inactive 45deg
}

decoration {
  rounding = 8
  blur {
    enabled = true
    passes = 2
  }
}

animations {
  bezier = smooth, 0.22, 1, 0.36, 1
  animation = windows, 1, 4, smooth, popin 80%
}

windowrule = opacity 0.92, match:class = Alacritty`;

  const { lua, unknown } = convertText(input, "hyprland.conf");

  assert.deepEqual(unknown, []);
  assert.match(lua, /local active = "rgba\(89b4faee\)"/);
  assert.match(lua, /hl.config\(\{/);
  assert.match(lua, /active_border = \{/);
  assert.match(lua, /colors = \{ active, inactive \}/);
  assert.match(lua, /angle = 45/);
  assert.match(lua, /blur = \{/);
  assert.match(lua, /hl.curve\("smooth"/);
  assert.match(lua, /hl.animation\(\{/);
  assert.match(lua, /hl.window_rule\(\{/);
  assert.match(lua, /match = \{/);
});

test("convertText keeps review notes for unknown top-level assignments and parse issues", () => {
  const { lua, unknown } = convertText("mystery = value\nbroken {\n");

  assert.deepEqual(unknown, [
    "line 2: unclosed block 'broken'",
    "line 1: unconverted top-level assignment mystery = value"
  ]);
  assert.match(lua, /Review required/);
  assert.match(lua, /line 1: unconverted top-level assignment mystery = value/);
  assert.match(lua, /line 2: unclosed block 'broken'/);
});

test("convertText emits common full-config directives", () => {
  const input = `$mainMod = SUPER

source = ./colors.conf
monitor = DP-1, 2560x1440@165, 0x0, 1
env = XCURSOR_SIZE, 24
exec-once = waybar
exec = mako
workspace = 1, monitor:DP-1, default:true
bind = $mainMod, Return, exec, foot
bindl = , XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
windowrulev2 = float, match:class = pinentry

device {
  name = epic-mouse-v1
  sensitivity = -0.5
}

gestures {
  workspace_swipe = true
}

gesture {
  fingers = 3
  direction = horizontal
  action = workspace
}`;

  const { lua, unknown } = convertText(input, "full.conf");

  assert.deepEqual(unknown, ["line 3: source = ./colors.conf needs manual require() path review"]);
  assert.match(lua, /local mainMod = "SUPER"/);
  assert.match(lua, /-- source = \.\/colors\.conf/);
  assert.match(lua, /hl.monitor\(\{/);
  assert.match(lua, /output = "DP-1"/);
  assert.match(lua, /hl.env\("XCURSOR_SIZE", "24"\)/);
  assert.match(lua, /hl.exec_cmd\("mako"\)/);
  assert.match(lua, /hl.on\("hyprland.start", function\(\)/);
  assert.match(lua, /hl.workspace_rule\(\{/);
  assert.match(lua, /monitor = "DP-1"/);
  assert.match(lua, /default = true/);
  assert.match(lua, /hl.window_rule\(\{/);
  assert.match(lua, /hl.device\(\{/);
  assert.match(lua, /gestures = \{/);
  assert.match(lua, /hl.gesture\(\{/);
  assert.match(lua, /hl.bind\(mainMod \.\. " \+ Return", hl\.dsp\.exec_cmd\("foot"\)\)/);
  assert.match(lua, /locked = true/);
});

test("Python CLI matches browser converter for common full-config directives", () => {
  const input = `$mainMod = SUPER
monitor = , preferred, auto, auto
env = XCURSOR_SIZE, 24
exec-once = waybar
bind = $mainMod, Return, exec, foot
workspace = 1, monitor:DP-1`;

  const dir = mkdtempSync(join(tmpdir(), "hypr2lua-"));
  const inputPath = join(dir, "full.conf");
  writeFileSync(inputPath, input);

  const jsLua = convertText(input, inputPath).lua.replace("-- Generated by hypr2lua-web.", "-- Generated by scripts/hypr2lua.");
  const pyLua = execFileSync("python3", ["docs/hypr2lua.py", inputPath], {
    cwd: process.cwd(),
    encoding: "utf8"
  });

  assert.equal(pyLua, jsLua);
});
